name: Build
permissions: {}

on:
  repository_dispatch:
    types: [build-command]

jobs:
  _isCheck_build:
    name: Build Job
    runs-on: ubuntu-latest
    # This job only runs if the short SHA from the command matches the start of the PR's head SHA.
    if: |
      github.event.client_payload.slash_command.args.named.sha != '' &&
      startsWith(
        github.event.client_payload.pull_request.head.sha, 
        github.event.client_payload.slash_command.args.named.sha
      )
    steps:
      - name: Simulate build process
        run: echo "Building the project..."